// packages/kit-vue/src/hh-footer/hh-footer.vue

<template>
  <div class="hh-footer" :class="`hh-footer-grids-${currentGroups.length}`">
    <div class="hh-footer-content">
      <div class="hh-footer-links-container">
        <div class="hh-footer-links" v-for="(group, gIdx) in currentGroups" :key="gIdx">
          <h3 class="hh-footer-links-title">{{ group.title }}</h3>
          <ul class="hh-footer-links-list">
            <li class="hh-footer-links-item" v-for="(link, lIdx) in group.links" :key="lIdx">
              <template v-if="isImageDialogLink(link)">
                <a href="javascript:;" @click.prevent="openImageDialog(link)">{{ link.label }}</a>
              </template>
              <template v-else>
                <a :href="link.href" :target="link.external === false ? undefined : '_blank'">{{ link.label }}</a>
              </template>
            </li>
          </ul>
        </div>
      </div>
      <p class="hh-footer-copyright">{{ currentCopyright }}</p>
    </div>
  </div>

  <hh-image-dialog
    v-model="dialogVisible"
    :image="dialogImage"
    :text="dialogText"
  />
</template>

<script setup lang="ts">
  import { computed, ref } from "vue";
  import hhFooterData from "@houheaven/kit-assets/data/hh-footer-data";
  import type { FooterGroup, FooterLink, FooterLinkImageDialog } from "@houheaven/kit-assets/data/hh-footer-types";
  import hhImageDialog from "../hh-image-dialog/hh-image-dialog.vue";

  interface IfFooterProps {
    // 分组导航数据
    groups?: FooterGroup[];
    // 底部版权文字
    copyright?: string;
    // 开启后直接使用 houheaven 默认数据，优先级高于其它 props
    useHouheavenData?: boolean;
  }

  const props = withDefaults(defineProps<IfFooterProps>(), {
    groups: () => [],
    copyright: "",
    useHouheavenData: false,
  });

  defineOptions({ name: "hh-footer" });

  // useHouheavenData 优先级最高：开启后所有字段一律取 houheaven 内置数据
  const currentGroups = computed<FooterGroup[]>(() => (props.useHouheavenData ? hhFooterData.groups : props.groups));
  const currentCopyright = computed(() => (props.useHouheavenData ? hhFooterData.copyright : props.copyright));

  // 图片弹窗状态
  const dialogVisible = ref(false);
  const dialogImage = ref("");
  const dialogText = ref("");

  // 类型守卫:配合模板中 v-if 触发 TS 类型收窄
  function isImageDialogLink(link: FooterLink): link is FooterLinkImageDialog {
    return link.type === "image-dialog";
  }

  function openImageDialog(link: FooterLinkImageDialog): void {
    dialogImage.value = link.image;
    dialogText.value = link.text ?? "";
    dialogVisible.value = true;
  }
</script>

<style lang="less">
  .hh-footer {
    --content-width: 750px;
    --grid-columns: 4;
    --grid-gap: 40px;

    left: 0;
    bottom: 0;
    width: 100%;
    background: #2a2d33;
    padding: 40px 0 30px;

    * {
      margin: 0;
      padding: 0;
      box-sizing: border-box;
    }

    &-grids-3 {
      --content-width: 560px;
      --grid-columns: 3;
    }
    &-grids-2 {
      --content-width: 360px;
      --grid-columns: 2;
    }
    &-grids-1 {
      --content-width: 200px;
      --grid-columns: 1;
    }

    &-content {
      width: var(--content-width);
      margin: auto;
      border: 0px solid #f00;
    }
    &-links-container {
      display: grid;
      grid-template-columns: repeat(var(--grid-columns), 1fr);
      gap: var(--grid-gap);
    }
    &-links {
      box-sizing: border-box;
      border: 0px solid #f00;
      &-title {
        font: 15px/1.7em "微软雅黑";
        color: #818692;
      }
      &-item {
        list-style-position: outside;
        list-style-type: none;
      }
      a {
        display: inline-block;
        font: 13px/1.6em "微软雅黑";
        color: #fff;
        transition: all 0.2s ease 0s;
        text-decoration: none;
        outline: none;

        &:hover {
          color: #47c1f4;
        }
      }
    }
    &-copyright {
      font: 13px/20px "微软雅黑";
      color: #818692;
      text-align: center;
      padding-top: 30px;
      clear: both;
    }

    @media (max-width: 719px) {
      & {
        --content-width: 80%;
        --grid-columns: 2;
        --grid-gap: 0;
        padding: 30px 0;
      }
      &-links {
        margin: 10px 0;
      }
      &-copyright {
        padding-top: 15px;
      }
    }
  }
</style>

// packages/kit-react/src/hh-footer/hh-footer.tsx

/* eslint-disable @typescript-eslint/naming-convention, react/require-default-props, no-script-url, react/jsx-no-script-url, react/no-array-index-key, no-undefined, react/boolean-prop-naming */
// 全文件禁用与仓库其它场景冲突的规则:
// - naming-convention:PascalCase 组件必须与仓库变量 camelCase 规则冲突
// - require-default-props:React 侧使用参数默认值代替 defaultProps
// - script-url:footer link 使用 href="javascript:;" 拦截默认跳转,行为同 kit-vue
// - no-array-index-key:groups/links 是纯静态数组,索引即稳定 key
// - no-undefined:target/rel 未启用时传 undefined 才能避免属性生成
// - boolean-prop-naming:useHouheavenData 保持与 kit-vue prop 命名对齐

import React, { useCallback, useState } from "react";
import type { MouseEvent as ReactMouseEvent } from "react";
import hhFooterData from "@houheaven/kit-assets/data/hh-footer-data";
import type { FooterGroup, FooterLink, FooterLinkImageDialog } from "@houheaven/kit-assets/data/hh-footer-types";
import HhImageDialog from "../hh-image-dialog/hh-image-dialog.tsx";
import "./hh-footer.css";

interface HhFooterProps {
  // 分组导航数据
  groups?: FooterGroup[];
  // 底部版权文字
  copyright?: string;
  // 开启后直接使用 houheaven 默认数据,优先级高于其它 props
  useHouheavenData?: boolean;
}

// 类型守卫:让 TS 缩小到 image-dialog 分支
function isImageDialogLink(link: FooterLink): link is FooterLinkImageDialog {
  return link.type === "image-dialog";
}

interface FooterLinkItemProps {
  link: FooterLink;
  onImageDialog: (link: FooterLinkImageDialog) => void;
}

// 抽出子组件规避 react/jsx-no-bind,使 map 循环里没有内联箭头
const FooterLinkItem = (itemProps: FooterLinkItemProps): React.JSX.Element => {
  const { link, onImageDialog } = itemProps;
  const handleImageDialog = useCallback(
    (evt: ReactMouseEvent<HTMLAnchorElement>): void => {
      evt.preventDefault();
      if (isImageDialogLink(link)) onImageDialog(link);
    },
    [link, onImageDialog]
  );
  if (isImageDialogLink(link)) {
    return (
      <a href="javascript:;" onClick={handleImageDialog}>
        {link.label}
      </a>
    );
  }
  const isExternal = link.external !== false;
  return (
    <a
      href={link.href}
      rel={isExternal ? "noreferrer" : undefined}
      target={isExternal ? "_blank" : undefined}
    >
      {link.label}
    </a>
  );
};

const HhFooter = (props: HhFooterProps): React.JSX.Element => {
  const { groups = [], copyright = "", useHouheavenData = false } = props;
  const currentGroups: FooterGroup[] = useHouheavenData ? hhFooterData.groups : groups;
  const currentCopyright: string = useHouheavenData ? hhFooterData.copyright : copyright;

  const [isDialogOpen, setIsDialogOpen] = useState<boolean>(false);
  const [dialogImage, setDialogImage] = useState<string>("");
  const [dialogText, setDialogText] = useState<string>("");

  const openImageDialog = useCallback((link: FooterLinkImageDialog): void => {
    setDialogImage(link.image);
    setDialogText(link.text ?? "");
    setIsDialogOpen(true);
  }, []);

  return (
    <>
      <div className={`hh-footer hh-footer-grids-${currentGroups.length}`}>
        <div className="hh-footer-content">
          <div className="hh-footer-links-container">
            {currentGroups.map((group, gIdx) => (
              <div key={gIdx} className="hh-footer-links">
                <h3 className="hh-footer-links-title">{group.title}</h3>
                <ul className="hh-footer-links-list">
                  {group.links.map((link, lIdx) => (
                    <li key={lIdx} className="hh-footer-links-item">
                      <FooterLinkItem link={link} onImageDialog={openImageDialog} />
                    </li>
                  ))}
                </ul>
              </div>
            ))}
          </div>
          <p className="hh-footer-copyright">{currentCopyright}</p>
        </div>
      </div>
      <HhImageDialog
        image={dialogImage}
        isOpen={isDialogOpen}
        text={dialogText}
        onOpenChange={setIsDialogOpen}
      />
    </>
  );
};

export default HhFooter;
export type {
  HhFooterProps,
};
