// apps/demo-vue/src/views/hh-image-dialog-view.vue

<template>
  <div class="hh-image-dialog-view">
    <header class="page-header">
      <router-link to="/" class="back-link">← 返回首页</router-link>
      <h1>hhImageDialog</h1>
      <p class="description">简易图片弹窗组件,用于展示二维码等图片。通过 <code>:show</code> 控制显示,点击遮罩或按 ESC 触发 <code>@close</code>。</p>
    </header>

    <section class="demo-section">
      <h2>基础用法</h2>
      <p class="section-desc">
        通过 <code>:show</code> 控制显示状态;<code>src</code> 指定图片地址,<code>caption</code> 指定图片下方说明文字;<code>@close</code> 在点击遮罩或 ESC 时触发。
      </p>
      <div class="preview">
        <v-button type="primary" @click="visible = true">显示图片</v-button>
      </div>
      <hh-image-dialog v-model="visible" :image="qrcode" text="扫码关注 houheaven" />
    </section>

    <section class="demo-section">
      <h2>API</h2>
      <table class="api-table">
        <thead>
          <tr>
            <th>类别</th>
            <th>名称</th>
            <th>说明</th>
            <th>类型 / 默认值</th>
          </tr>
        </thead>
        <tbody>
          <tr>
            <td>Props</td>
            <td>show</td>
            <td>是否显示弹窗</td>
            <td>boolean / —</td>
          </tr>
          <tr>
            <td>Props</td>
            <td>src</td>
            <td>图片地址</td>
            <td>string / —</td>
          </tr>
          <tr>
            <td>Props</td>
            <td>alt</td>
            <td>图片替代文本</td>
            <td>string / ""</td>
          </tr>
          <tr>
            <td>Props</td>
            <td>caption</td>
            <td>图片下方说明文字</td>
            <td>string / ""</td>
          </tr>
          <tr>
            <td>Events</td>
            <td>close</td>
            <td>点击遮罩或按 ESC 时触发</td>
            <td>—</td>
          </tr>
        </tbody>
      </table>
    </section>
  </div>
</template>

<script setup lang="ts">
  import { ref } from "vue";
  import hhImageDialog from "@houheaven/kit-vue/hh-image-dialog";
  import "@houheaven/kit-vue/hh-image-dialog/style.css";
  import qrcode from "@houheaven/kit-assets/assets/wx-mp-houheaven.jpg";
  import VButton from "../components/v-button.vue";

  const visible = ref(false);
</script>

<style scoped>
  .hh-image-dialog-view {
    min-height: 100vh;
    background: #f7f8fa;
  }

  .page-header {
    max-width: 960px;
    margin: 0 auto;
    padding: 40px 24px 24px;
  }

  .back-link {
    display: inline-block;
    color: #667eea;
    text-decoration: none;
    font-size: 14px;
    margin-bottom: 16px;
  }

  .back-link:hover {
    text-decoration: underline;
  }

  .page-header h1 {
    margin: 0 0 8px;
    font-size: 32px;
    font-weight: 600;
    color: #2a2d33;
  }

  .description {
    margin: 0;
    font-size: 14px;
    color: #6b7280;
    line-height: 1.6;
  }

  .description code {
    background: #f3f4f6;
    padding: 2px 6px;
    border-radius: 3px;
    font-size: 12px;
    font-family: "SFMono-Regular", Consolas, monospace;
  }

  .demo-section {
    max-width: 960px;
    margin: 24px auto;
    padding: 24px;
    background: #fff;
    border-radius: 8px;
    box-shadow: 0 1px 3px rgba(0, 0, 0, 0.05);
  }

  .demo-section h2 {
    margin: 0 0 8px;
    font-size: 18px;
    font-weight: 600;
    color: #2a2d33;
  }

  .section-desc {
    margin: 0 0 16px;
    font-size: 13px;
    color: #6b7280;
    line-height: 1.6;
  }

  .section-desc code {
    background: #f3f4f6;
    padding: 2px 6px;
    border-radius: 3px;
    font-size: 12px;
    font-family: "SFMono-Regular", Consolas, monospace;
  }

  .preview {
    padding: 24px;
    border: 1px solid #e5e7eb;
    border-radius: 6px;
  }

  .api-table {
    width: 100%;
    border-collapse: collapse;
    font-size: 13px;
  }

  .api-table th,
  .api-table td {
    padding: 10px 12px;
    text-align: left;
    border-bottom: 1px solid #e5e7eb;
  }

  .api-table th {
    background: #f9fafb;
    color: #4b5563;
    font-weight: 600;
  }

  .api-table td {
    color: #374151;
  }
</style>

// apps/demo-react/src/views/hh-image-dialog-view.tsx

/* eslint-disable @typescript-eslint/naming-convention, react/forbid-component-props */
// - naming-convention:PascalCase 组件必须与仓库变量 camelCase 规则冲突
// - forbid-component-props:react-router-dom 的 Link 使用 className 是官方规范

import React, { useCallback, useState } from "react";
import { Link } from "react-router-dom";
import HhImageDialog from "@houheaven/kit-react/hh-image-dialog";
import qrcode from "@houheaven/kit-assets/assets/wx-mp-houheaven.jpg";
import VButton from "../components/v-button.tsx";
import "./hh-image-dialog-view.css";

const HhImageDialogView = (): React.JSX.Element => {
  const [isVisible, setIsVisible] = useState<boolean>(false);
  const handleOpen = useCallback((): void => {
    setIsVisible(true);
  }, []);

  return (
    <div className="hh-image-dialog-view">
      <header className="page-header">
        <Link className="back-link" to="/">← 返回首页</Link>
        <h1>hhImageDialog</h1>
        <p className="description">
          简易图片弹窗组件,用于展示二维码等图片。通过
          {" "}
          <code>isOpen</code>
          {" "}
          控制显示,点击遮罩或按 ESC 触发
          {" "}
          <code>onOpenChange(false)</code>
          。
        </p>
      </header>

      <section className="demo-section">
        <h2>基础用法</h2>
        <p className="section-desc">
          通过
          {" "}
          <code>isOpen</code>
          {" "}
          +
          {" "}
          <code>onOpenChange</code>
          {" "}
          受控;
          <code>image</code>
          {" "}
          指定图片地址,
          <code>text</code>
          {" "}
          指定图片下方说明文字。
        </p>
        <div className="preview">
          <VButton type="primary" onClick={handleOpen}>显示图片</VButton>
        </div>
        <HhImageDialog
          image={qrcode}
          isOpen={isVisible}
          text="扫码关注 houheaven"
          onOpenChange={setIsVisible}
        />
      </section>

      <section className="demo-section">
        <h2>API</h2>
        <table className="api-table">
          <thead>
            <tr>
              <th>类别</th>
              <th>名称</th>
              <th>说明</th>
              <th>类型 / 默认值</th>
            </tr>
          </thead>
          <tbody>
            <tr>
              <td>Props</td>
              <td>isOpen</td>
              <td>是否显示弹窗</td>
              <td>boolean / —</td>
            </tr>
            <tr>
              <td>Props</td>
              <td>onOpenChange</td>
              <td>显隐变更回调(点击遮罩、按 ESC 会传 false)</td>
              <td>(next: boolean) =&gt; void / —</td>
            </tr>
            <tr>
              <td>Props</td>
              <td>image</td>
              <td>图片地址</td>
              <td>string / —</td>
            </tr>
            <tr>
              <td>Props</td>
              <td>text</td>
              <td>图片下方说明文字</td>
              <td>string / &quot;&quot;</td>
            </tr>
          </tbody>
        </table>
      </section>
    </div>
  );
};

export default HhImageDialogView;
