// apps/demo-vue/src/App.vue

<template>
  <div style="padding: 24px">
    <h1>hh-kit Vue Demo</h1>
    <hh-button type="primary" @click="console.log('primary clicked')">Primary</hh-button>
    <hh-button>Default</hh-button>
  </div>
</template>

<script setup lang="ts">
  import { HhButton } from "@houheaven/kit-vue";
</script>

// apps/demo-react/src/App.tsx
import { Button } from '@houheaven/kit-react'

export function App() {
  return (
    <div style={{ padding: 24 }}>
      <h1>hh-kit React Demo</h1>
      <Button type="primary" onClick={() => console.log('primary clicked')}>
        Primary
      </Button>
      <Button>Default</Button>
    </div>
  )
}
